In [1]:
import torch

x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [3]:
# y was created as a result of an operation, so it has a grad_fn
print(y.grad_fn)

In [8]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [9]:
a = torch.randn(2,2)
a = (( a*3) /(a-1))
print(a.requires_grad)

a.requires_grad_(True)

print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [10]:
# out contains 27 scalar
out.backward()

#print gradients d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
# vector with 3 elements
x = torch.randn(3, requires_grad=True)
print(x)

# y.data.norm() is equivalent to torch.sqrt(torch.sum(torch.pow(y, 2)))
# Euclidean norm of the tensor

y = x * 2
print(y)
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([-0.0911, -0.5621, -0.0451], requires_grad=True)
tensor([-0.1821, -1.1241, -0.0902], grad_fn=<MulBackward0>)
tensor([ -186.5152, -1151.0851,   -92.4076], grad_fn=<MulBackward0>)


In [15]:
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)

# why vector 0.1, 1.0, 0.0001?
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [16]:
print(x.requires_grad)

print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
