In [7]:
from __future__ import print_function
import torch
import numpy as np

x = torch.empty(5,3)
print (x)


tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.6423e-42, 0.0000e+00],
        [0.0000e+00, 3.5833e-14, 0.0000e+00]])


In [8]:
# construct randomly initialized matrix
x = torch.rand(5,3)
print (x)

tensor([[0.7848, 0.6036, 0.0524],
        [0.2038, 0.2866, 0.8084],
        [0.8100, 0.1398, 0.5143],
        [0.7171, 0.4245, 0.4150],
        [0.6497, 0.4454, 0.7331]])


In [9]:
#construct a matrix filled zeros and of dtype long
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9566,  0.0972, -0.0341],
        [-1.0936, -0.1803, -2.0771],
        [ 0.9367,  1.4410,  0.0566],
        [-1.2937, -0.3992,  0.5089],
        [-0.2590, -2.0443,  1.2980]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5,3)
print (y)

print ( x + y)

tensor([[0.8103, 0.8359, 0.0110],
        [0.7198, 0.3076, 0.6832],
        [0.3610, 0.2106, 0.3006],
        [0.4417, 0.1559, 0.4684],
        [0.9822, 0.5739, 0.4693]])
tensor([[ 1.7669,  0.9330, -0.0231],
        [-0.3738,  0.1273, -1.3940],
        [ 1.2977,  1.6516,  0.3572],
        [-0.8520, -0.2434,  0.9773],
        [ 0.7232, -1.4704,  1.7673]])


In [15]:
print(torch.add(x,y))

tensor([[ 1.7669,  0.9330, -0.0231],
        [-0.3738,  0.1273, -1.3940],
        [ 1.2977,  1.6516,  0.3572],
        [-0.8520, -0.2434,  0.9773],
        [ 0.7232, -1.4704,  1.7673]])


In [16]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 1.7669,  0.9330, -0.0231],
        [-0.3738,  0.1273, -1.3940],
        [ 1.2977,  1.6516,  0.3572],
        [-0.8520, -0.2434,  0.9773],
        [ 0.7232, -1.4704,  1.7673]])


In [17]:
y.add_(x)
print(y)

tensor([[ 1.7669,  0.9330, -0.0231],
        [-0.3738,  0.1273, -1.3940],
        [ 1.2977,  1.6516,  0.3572],
        [-0.8520, -0.2434,  0.9773],
        [ 0.7232, -1.4704,  1.7673]])


In [22]:
print(x[:,1])

tensor([ 0.0972, -0.1803,  1.4410, -0.3992, -2.0443])


In [30]:
x = torch.rand(4,4)

print (x)

y = x.view(16) # turns into 16 element vector

print (y)

z = x.view(-1,8) # -1 is inferred from 8 columns

print (z)

print(x.size() , y.size(), z.size())



tensor([[0.1543, 0.2799, 0.9314, 0.0080],
        [0.7056, 0.4298, 0.7164, 0.0554],
        [0.4981, 0.2363, 0.7104, 0.9398],
        [0.3726, 0.1917, 0.1160, 0.3298]])
tensor([0.1543, 0.2799, 0.9314, 0.0080, 0.7056, 0.4298, 0.7164, 0.0554, 0.4981,
        0.2363, 0.7104, 0.9398, 0.3726, 0.1917, 0.1160, 0.3298])
tensor([[0.1543, 0.2799, 0.9314, 0.0080, 0.7056, 0.4298, 0.7164, 0.0554],
        [0.4981, 0.2363, 0.7104, 0.9398, 0.3726, 0.1917, 0.1160, 0.3298]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [31]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.5636])
-2.5635855197906494


In [32]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [33]:
# Numpy array changed in value but added to tensor
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [35]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [36]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-1.5636], device='cuda:0')
tensor([-1.5636], dtype=torch.float64)
