In [2]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, TensorDataset, DataLoader
import torchvision
import torchvision.transforms as transforms

import matplotlib.pyplot as plt
import numpy as np

In [13]:
# 1d array
x1 = torch.Tensor([1,2,3,4])

# 2d array
x2 = torch.Tensor([[5,6,7,8], [9,10,11,12]])

x3 = torch.Tensor([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]]])

In [14]:
print (x1)

print (x2)

print (x3)

tensor([1., 2., 3., 4.])
tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]])


In [15]:
print(x1[0])

tensor(1.)


In [16]:
print(x2[0,0])

tensor(5.)


In [17]:
print(x2[0,:])

tensor([5., 6., 7., 8.])


In [18]:
print(x2[:,2])

tensor([ 7., 11.])


In [23]:
x2.size()
x3.size()

torch.Size([2, 2, 4])